### ISSUE TITLE
Punq is incompatible with Ubuntu 20.04

### ISSUE THREAD

**Issue by marevers** [mogenius/punq#26]
I wanted to test Punq, but it seems it is incompatible with Ubuntu 20.04.

Downloading the binary on Ubuntu 20.04 (in WSL) and running it results in the following errors:

```bash
punq
punq: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by punq)
punq: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by punq)
```

As per my version of Ubuntu 20.04, it has libc6 2.31 installed. Doing a kernel update is not viable.
This could be solved by building the executable on Ubuntu 20.04 instead of 22.04 - that should remove the dependency of libc6 2.32 and 2.34.

**Comment by delalikwami** [comment]
@marevers I was running into the same problem, but an alternate method that worked for me was to install punq using homebrew.

```sh
$ brew install --build-bottle punq
$ brew bottle punq
# this will generate a tar.gz in the current directory
$ brew install <punq-bottle-name>.tar.gz
```

**Comment by beneiltis** [comment]
Sorry for waiting so long. This wont happen again. 
I created a new github runner which now builds all stuff on 20.04 which solve this problem. 
punq-dev is already working as expected on ubuntu 20.04.

in 20min prod will be released as well. Would be great to know if it solves the problem for you.

Thx for reporting and have a greate day.

**Comment by beneiltis** [comment]
Ok release now available: punq/1.5.7
I will close this issue as soon as you guys give me feedback. 
On my ubuntu 20.04 everything is working now.

**Comment by beneiltis** [comment]
I am gone close this now because it should be solved.

**Comment by delalikwami** [comment]
Hi @beneiltis sorry about the delay, but I did get a chance to pull 1.5.8 and confirm that it's working as expected for me now. Thank you!
